### ISSUE TITLE
Add a new dataset & benchmark paper

### ISSUE THREAD

**Issue by Zhuofeng-Li** [PeterGriffinJin/Awesome-Language-Model-on-Graphs#14]
Hi Bowen,

Thanks for this comprehensive collection of works!

I want to share our recent TEG (textual-edge graph featuring rich
textual descriptions on nodes and edges) Datasets and Benchmark work published in NeurIPS 2024.

**TEG-DB: A Comprehensive Dataset and Benchmark of Textual-Edge Graphs.** `NeurIPS 2024`

_Zhuofeng Li*, Zixing Gou*, Xiangnan Zhang, Zhongyuan Liu, Sirui Li, Yuntong Hu, Chen Ling,
Zheng Zhang, Liang Zhao._ [[pdf](https://arxiv.org/abs/2406.10310)][[code](https://github.com/Zhuofeng-Li/TEG-Benchmark/tree/main)][[datasets](https://huggingface.co/datasets/ZhuofengLi/TEG-Datasets/tree/main)], 2024.9.

Best,
Zhuofeng

**Comment by PeterGriffinJin** [comment]
Hi Zhuofeng,

Thank you for bringing up this awesome paper. It is added to the repo.

Best,
Bowen
