### ISSUE TITLE
Are Large-Language Models Graph Algorithmic Reasoners?

### ISSUE THREAD

**Issue by ataylor24** [PeterGriffinJin/Awesome-Language-Model-on-Graphs#17]
1. **Are Large-Language Models Graph Algorithmic Reasoners?** `[preprint]`

    *Alexander K Taylor, Anthony Cuturrufo, Vishal Yathish, Mingyu Derek Ma, Wei Wang.* [[PDF](https://arxiv.org/pdf/2410.22597)] [[Code](https://github.com/ataylor24/MAGMA)], 2024.10, ![](https://img.shields.io/badge/DecoderOnly-blue) ![](https://img.shields.io/badge/LLM-red)

**Comment by PeterGriffinJin** [comment]
Thank you for providing this nice paper! It is added in the repo.

Best,
Bowen
