### ISSUE TITLE
Knowledge Graph Prompting for Multi-Document Question Answering

### ISSUE THREAD

**Issue by yuwvandy** [PeterGriffinJin/Awesome-Language-Model-on-Graphs#3]
Dear Esteemed Authors,

I hope this message finds you well. I recently had the opportunity to read your thorough and timely survey on the integration of Large Language Models (LLMs) with Graphs and learned a lot.

In parallel, my colleagues and I have conducted research in a closely related area. Our recent paper explores the enhancement of prompt content through knowledge graph traversal, which aligns closely with the themes of your survey. Given the relevance and potential contribution to the ongoing discourse in your work, I kindly inquire if there is an opportunity to include our research in your survey. Thank you for your consideration!

1. **[Knowledge Graph Prompting for Multi-Document Question Answering].** `[AAAI 2024]`

    *[Yu Wang, Nedim Lipka, Ryan Rossi, Alex Siu, Ruiyi Zhang, Tyler Derr].* [[PDF]](https://arxiv.org/abs/2308.11730)[[Code]](https://github.com/YuWVandy/KG-LLM-MDQA), 2023.8, ![](https://img.shields.io/badge/[architecture]-blue) ![](https://img.shields.io/badge/[size]-red)

**Comment by PeterGriffinJin** [comment]
Hi Yu,

Thank you so much for bringing this brilliant work!

I have added it to the repo and will try to add it into the next version of our survey paper.

Best,
Bowen

**Comment by yuwvandy** [comment]
Thank you, Bowen!

Best,
Yu Wang
