### ISSUE TITLE
A Potential Related Work

### ISSUE THREAD

**Issue by Samyu0304** [PeterGriffinJin/Awesome-Language-Model-on-Graphs#5]
Dear Authors,

Thanks for this wonderful survey and repo! We would like to introduce our related work on using the graph structure of general tasks to enhance complex reasoning with LLMs "Junchi Yu, Ran He, Rex, Ying. Thought Propagation: An Analogical Approach to Complex Reasoning with Large Language Models". Apart from general reasoning tasks, our method also performs well on the Shortest-path Reasoning problem on graphs. 

We hope our work could further enrich your awesome repo and survey ☺️ !

Best,
Junchi Yu

**Comment by PeterGriffinJin** [comment]
Hi Junchi,

Thank you for bringing up this great paper! I have added it to the repo.

Best,
Bowen
