### ISSUE TITLE
A framework to employ LLMs for entity alignment in knowledge graphs

### ISSUE THREAD

**Issue by chensyCN** [PeterGriffinJin/Awesome-Language-Model-on-Graphs#9]
1. **Entity Alignment with Noisy Annotations from Large Language Models.** `preprint`

    *Shengyuan Chen, Qinggang Zhang, Junnan Dong, Wen Hua, Qing Li, Xiao Huang.* [[PDF](https://arxiv.org/pdf/2405.16806)] [[Code](https://github.com/chensyCN/llm4ea_official)], 2024.5, ![](https://img.shields.io/badge/[DecoderOnly]-blue) ![](https://img.shields.io/badge/[LLM]-red)

**Comment by PeterGriffinJin** [comment]
Thanks for bringing up this paper! It is added to the repo. :)
